CREATE DATABASE IF NOT EXISTS AcervoDB;
USE AcervoDB;

CREATE TABLE IF NOT EXISTS TB_ACERVO (
    ACERVO_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    ANO INT NOT NULL,
    FLAG_EMPRESTADO BOOLEAN NOT NULL,
    CDU VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_AUTOR (
    AUTOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    NACIONALIDADE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_ACERVO_AUTOR (
    ACERVO_ID INT,
    AUTOR_ID INT,
    PRIMARY KEY (ACERVO_ID, AUTOR_ID),
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID),
    FOREIGN KEY (AUTOR_ID) REFERENCES TB_AUTOR(AUTOR_ID)
);

CREATE TABLE IF NOT EXISTS TB_PALAVRA_CHAVE (
    PALAVRA_ID INT PRIMARY KEY AUTO_INCREMENT,
    PALAVRA_CHAVE VARCHAR(255) NOT NULL,
    ACERVO_ID INT,
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID)
);

CREATE TABLE IF NOT EXISTS TB_ACERVO_MIDIAS (
    ACERVO_MIDIAS_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(255) NOT NULL,
    PRODUTORA VARCHAR(255) NOT NULL,
    ISBN VARCHAR(255),
    ACERVO_ID INT,
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID)
);

CREATE TABLE IF NOT EXISTS TB_ACERVO_MAPAS (
    ACERVO_MAPAS_ID INT PRIMARY KEY AUTO_INCREMENT,
    LOCALIZACAO VARCHAR(255) NOT NULL,
    EDICAO INT NOT NULL,
    ACERVO_ID INT,
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID)
);

CREATE TABLE IF NOT EXISTS TB_ACERVO_ACADEMICOS (
    ACERVO_ACADEMICOS_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(255) NOT NULL,
    EDITORA VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    DOI VARCHAR(255),
    ACERVO_ID INT,
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID)
);

CREATE TABLE IF NOT EXISTS TB_ACERVO_CARTAZES (
    ACERVO_CARTAZES_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(255) NOT NULL,
    ACERVO_ID INT,
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID)
);

CREATE TABLE IF NOT EXISTS TB_ACERVO_LIVROS (
    ACERVO_LIVROS_ID INT PRIMARY KEY AUTO_INCREMENT,
    QTD_PAGINAS INT NOT NULL,
    EDICAO INT NOT NULL,
    EDITORA VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    ISBN VARCHAR(255),
    ACERVO_ID INT,
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID)
);

CREATE TABLE IF NOT EXISTS TB_ACERVO_PERIODICOS (
    ACERVO_PERIODICOS_ID INT PRIMARY KEY AUTO_INCREMENT,
    QTD_PAGINAS INT NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    EDICAO INT NOT NULL,
    EDITORA VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    ISBN VARCHAR(255),
    ACERVO_ID INT,
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID)
);

CREATE TABLE IF NOT EXISTS TB_ACERVO_RELATORIOS (
    ACERVO_RELATORIOS_ID INT PRIMARY KEY AUTO_INCREMENT,
    QTD_PAGINAS INT NOT NULL,
    EDITORA VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    ACERVO_ID INT,
    FOREIGN KEY (ACERVO_ID) REFERENCES TB_ACERVO(ACERVO_ID)
);